version: '3.8'

services:
  app:
    image: laravelsail/php82-composer
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
